name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - staging

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read & Increment Version
        id: version
        run: |
          VERSION=$(cat VERSION)
          NEW_VERSION=$(printf "%06d" $((10#$VERSION + 1)))  # Ensure six-digit format
          echo $NEW_VERSION > VERSION
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Commit Updated Version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add VERSION
          git commit -m "Bump version to $VERSION"
          git push
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
         docker build -t ghcr.io/${{ github.actor }}/hngstage:${{ env.VERSION }} -f NumberClassificationApi/Dockerfile .
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/hngstage:${{ env.VERSION }}
