name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - staging

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit the version bump
      packages: write  # Needed to push to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for accurate version bumping
          fetch-depth: 0

      - name: Read & Increment Version
        id: version
        run: |
          # Create the VERSION file if it doesn't exist
          if [ ! -f VERSION ]; then
            echo "000000" > VERSION
          fi
          
          CURRENT_VERSION=$(cat VERSION)
          # Increment the version number safely
          NEW_VERSION=$(printf "%06d" $((10#$CURRENT_VERSION + 1)))
          
          echo "Old version: $CURRENT_VERSION, New version: $NEW_VERSION"
          echo $NEW_VERSION > VERSION
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit Updated Version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Bump version to ${{ env.VERSION }}"
            git push
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in, secure token

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./NumberClassificationApi/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/hngstage:${{ env.VERSION }}
