name: Deploy to EC2 on Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required for pushing to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/kiki-user1/HngStageOneProject:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login ghcr.io -u kiki-user1 -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/kiki-user1/HngStageOneProject:${{ github.sha }}
            docker stop HngStageOneProject || true
            docker rm HngStageOneProject || true
            docker run -d --name HngStageOneProject -p 80:80 ghcr.io/kiki-user1/HngStageOneProject:${{ github.sha }}
